version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: retail_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: retail_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  airflow-standalone:
    image: apache/airflow:2.8.1-python3.11
    container_name: official_airflow_webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=retail_airflow_secret_key
      - _PIP_ADDITIONAL_REQUIREMENTS=pandas psycopg2-binary
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./utils:/opt/airflow/utils
      - ./config:/opt/airflow/config
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: standalone
    depends_on:
      postgres_db:
        condition: service_healthy

volumes:
  postgres_data:
